# Generated by Django 5.1 on 2024-09-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
