# Generated by Django 5.1.1 on 2024-09-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "cuisine_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "opening_hours",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("price_range", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "google_place_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("reviews", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
